/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./components/base/BaseAlert.vue')['default']
    BaseDatePicker: typeof import('./components/base/BaseDatePicker.vue')['default']
    BaseFileInput: typeof import('./components/base/BaseFileInput.vue')['default']
    BaseFileUploader: typeof import('./components/base/BaseFileUploader.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./components/base/BaseModal.vue')['default']
    BaseSelect: typeof import('./components/base/BaseSelect.vue')['default']
    BaseTextarea: typeof import('./components/base/BaseTextarea.vue')['default']
    BaseTooltip: typeof import('./components/base/BaseTooltip.vue')['default']
    CoreAdBlockDetector: typeof import('./components/core/CoreAdBlockDetector.vue')['default']
    CoreAppBar: typeof import('./components/core/CoreAppBar.vue')['default']
    CoreDrawer: typeof import('./components/core/drawer/CoreDrawer.vue')['default']
    CoreDrawerClose: typeof import('./components/core/drawer/CoreDrawerClose.vue')['default']
    CoreLoader: typeof import('./components/core/CoreLoader.vue')['default']
    CoreOfflineDetector: typeof import('./components/core/CoreOfflineDetector.vue')['default']
    CoreSnackbar: typeof import('./components/core/CoreSnackbar.vue')['default']
    Example: typeof import('./components/Example.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
